# Generated by Django 4.1.6 on 2023-02-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_student_country_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='l_name',
        ),
        migrations.AddField(
            model_name='student',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
